version: "3.9"

services:
  auto-gpt:
    container_name: auto-gpt
    restart: unless-stopped
    build:
      context: ../
    stdin_open: true
    tty: true
    volumes:
      - ../outputs:/app/outputs:Z
    env_file:
      - ./.env
  
  redis:
    image: redis/redis-stack:latest # use redis/redis-stack-server:latest for Production deployment without RedisInsight
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      REDIS_ARGS: --requirepass $REDIS_PASSWORD # value taken from REDIS_PASSWORD=secret in .env
    env_file:
      - ./.env
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    driver: local
